# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cal.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.clockWidget = QtWidgets.QWidget(self.centralwidget)
        self.clockWidget.setMinimumSize(QtCore.QSize(181, 111))
        self.clockWidget.setMaximumSize(QtCore.QSize(16777215, 171))
        self.clockWidget.setObjectName("clockWidget")
        self.lcdTens = QtWidgets.QLCDNumber(self.clockWidget)
        self.lcdTens.setGeometry(QtCore.QRect(100, 20, 41, 71))
        font = QtGui.QFont()
        font.setKerning(True)
        self.lcdTens.setFont(font)
        self.lcdTens.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcdTens.setSmallDecimalPoint(False)
        self.lcdTens.setDigitCount(1)
        self.lcdTens.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdTens.setProperty("intValue", 0)
        self.lcdTens.setObjectName("lcdTens")
        self.lcdHour = QtWidgets.QLCDNumber(self.clockWidget)
        self.lcdHour.setGeometry(QtCore.QRect(0, 20, 81, 71))
        font = QtGui.QFont()
        font.setKerning(True)
        self.lcdHour.setFont(font)
        self.lcdHour.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcdHour.setSmallDecimalPoint(False)
        self.lcdHour.setDigitCount(2)
        self.lcdHour.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdHour.setProperty("intValue", 0)
        self.lcdHour.setObjectName("lcdHour")
        self.lcdones = QtWidgets.QLCDNumber(self.clockWidget)
        self.lcdones.setGeometry(QtCore.QRect(140, 20, 41, 71))
        font = QtGui.QFont()
        font.setKerning(True)
        self.lcdones.setFont(font)
        self.lcdones.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcdones.setSmallDecimalPoint(False)
        self.lcdones.setDigitCount(1)
        self.lcdones.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdones.setProperty("intValue", 0)
        self.lcdones.setObjectName("lcdones")
        self.clockcolon = QtWidgets.QLabel(self.clockWidget)
        self.clockcolon.setGeometry(QtCore.QRect(70, 0, 31, 111))
        font = QtGui.QFont()
        font.setFamily("Liberation Mono")
        font.setPointSize(44)
        self.clockcolon.setFont(font)
        self.clockcolon.setObjectName("clockcolon")
        self.horizontalLayout.addWidget(self.clockWidget)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.nextVisitFrame = QtWidgets.QFrame(self.centralwidget)
        self.nextVisitFrame.setMinimumSize(QtCore.QSize(151, 171))
        self.nextVisitFrame.setMaximumSize(QtCore.QSize(151, 171))
        self.nextVisitFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.nextVisitFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.nextVisitFrame.setObjectName("nextVisitFrame")
        self.nextVisitGraphics = QtWidgets.QGraphicsView(self.nextVisitFrame)
        self.nextVisitGraphics.setGeometry(QtCore.QRect(0, 20, 150, 150))
        self.nextVisitGraphics.setObjectName("nextVisitGraphics")
        self.visitlabel = QtWidgets.QLabel(self.nextVisitFrame)
        self.visitlabel.setGeometry(QtCore.QRect(0, 0, 121, 21))
        self.visitlabel.setObjectName("visitlabel")
        self.horizontalLayout.addWidget(self.nextVisitFrame)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.day1 = QtWidgets.QWidget(self.centralwidget)
        self.day1.setMinimumSize(QtCore.QSize(129, 371))
        self.day1.setObjectName("day1")
        self.calview1 = QtWidgets.QGraphicsView(self.day1)
        self.calview1.setGeometry(QtCore.QRect(0, 30, 131, 341))
        self.calview1.setObjectName("calview1")
        self.daylabel1 = QtWidgets.QLabel(self.day1)
        self.daylabel1.setGeometry(QtCore.QRect(20, 10, 71, 17))
        self.daylabel1.setObjectName("daylabel1")
        self.horizontalLayout_2.addWidget(self.day1)
        self.day2 = QtWidgets.QWidget(self.centralwidget)
        self.day2.setMinimumSize(QtCore.QSize(129, 371))
        self.day2.setObjectName("day2")
        self.daylabel2 = QtWidgets.QLabel(self.day2)
        self.daylabel2.setGeometry(QtCore.QRect(20, 10, 71, 17))
        self.daylabel2.setObjectName("daylabel2")
        self.calview2 = QtWidgets.QGraphicsView(self.day2)
        self.calview2.setGeometry(QtCore.QRect(0, 30, 131, 341))
        self.calview2.setObjectName("calview2")
        self.horizontalLayout_2.addWidget(self.day2)
        self.day3 = QtWidgets.QWidget(self.centralwidget)
        self.day3.setMinimumSize(QtCore.QSize(129, 371))
        self.day3.setObjectName("day3")
        self.daylabel3 = QtWidgets.QLabel(self.day3)
        self.daylabel3.setGeometry(QtCore.QRect(20, 10, 81, 17))
        self.daylabel3.setObjectName("daylabel3")
        self.calview3 = QtWidgets.QGraphicsView(self.day3)
        self.calview3.setGeometry(QtCore.QRect(0, 30, 131, 341))
        self.calview3.setObjectName("calview3")
        self.horizontalLayout_2.addWidget(self.day3)
        self.day4 = QtWidgets.QWidget(self.centralwidget)
        self.day4.setMinimumSize(QtCore.QSize(129, 371))
        self.day4.setObjectName("day4")
        self.daylabel4 = QtWidgets.QLabel(self.day4)
        self.daylabel4.setGeometry(QtCore.QRect(20, 10, 71, 17))
        self.daylabel4.setObjectName("daylabel4")
        self.calview4 = QtWidgets.QGraphicsView(self.day4)
        self.calview4.setGeometry(QtCore.QRect(0, 30, 131, 341))
        self.calview4.setObjectName("calview4")
        self.horizontalLayout_2.addWidget(self.day4)
        self.day5 = QtWidgets.QWidget(self.centralwidget)
        self.day5.setMinimumSize(QtCore.QSize(129, 371))
        self.day5.setObjectName("day5")
        self.daylabel5 = QtWidgets.QLabel(self.day5)
        self.daylabel5.setGeometry(QtCore.QRect(20, 10, 81, 17))
        self.daylabel5.setObjectName("daylabel5")
        self.calview5 = QtWidgets.QGraphicsView(self.day5)
        self.calview5.setGeometry(QtCore.QRect(0, 30, 131, 341))
        self.calview5.setObjectName("calview5")
        self.horizontalLayout_2.addWidget(self.day5)
        self.day6 = QtWidgets.QWidget(self.centralwidget)
        self.day6.setMinimumSize(QtCore.QSize(129, 371))
        self.day6.setObjectName("day6")
        self.daylabel6 = QtWidgets.QLabel(self.day6)
        self.daylabel6.setGeometry(QtCore.QRect(20, 10, 61, 17))
        self.daylabel6.setObjectName("daylabel6")
        self.calview6 = QtWidgets.QGraphicsView(self.day6)
        self.calview6.setGeometry(QtCore.QRect(0, 30, 131, 341))
        self.calview6.setObjectName("calview6")
        self.horizontalLayout_2.addWidget(self.day6)
        self.day7 = QtWidgets.QWidget(self.centralwidget)
        self.day7.setMinimumSize(QtCore.QSize(129, 371))
        self.day7.setObjectName("day7")
        self.daylabel7 = QtWidgets.QLabel(self.day7)
        self.daylabel7.setGeometry(QtCore.QRect(20, 10, 61, 17))
        self.daylabel7.setObjectName("daylabel7")
        self.calview7 = QtWidgets.QGraphicsView(self.day7)
        self.calview7.setGeometry(QtCore.QRect(0, 30, 131, 341))
        self.calview7.setObjectName("calview7")
        self.horizontalLayout_2.addWidget(self.day7)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.nextVisitGraphics, self.calview1)
        MainWindow.setTabOrder(self.calview1, self.calview2)
        MainWindow.setTabOrder(self.calview2, self.calview3)
        MainWindow.setTabOrder(self.calview3, self.calview4)
        MainWindow.setTabOrder(self.calview4, self.calview5)
        MainWindow.setTabOrder(self.calview5, self.calview6)
        MainWindow.setTabOrder(self.calview6, self.calview7)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Paul\'s Calendar"))
        self.clockcolon.setText(_translate("MainWindow", ":"))
        self.visitlabel.setText(_translate("MainWindow", "Paul\'s Next Visit:"))
        self.daylabel1.setText(_translate("MainWindow", "Monday"))
        self.daylabel2.setText(_translate("MainWindow", "Tuesday"))
        self.daylabel3.setText(_translate("MainWindow", "Wednesday"))
        self.daylabel4.setText(_translate("MainWindow", "Thursday"))
        self.daylabel5.setText(_translate("MainWindow", "Friday"))
        self.daylabel6.setText(_translate("MainWindow", "Satuday"))
        self.daylabel7.setText(_translate("MainWindow", "Sunday"))

